### PR TITLE
Updated URSI

### PR DESCRIPTION
**Pull request by muttavarapu**
Updated URI for subject-tags.js and subject-edit-type.js
[asana task](https://app.asana.com/0/14721950943418/618003988795457/f)

### CODE REVIEW

**Comment by muttavarapu** [comment]
With the new permissions, the tests works fine without changing the USRI.

**Comment by ruwang** [comment]
I did the test last time during release test and got the error message. But
couple days later when I tried to fix it and the error msg's gone. Now I
see this fix and figure that could be due to the db refresh after the stage
release.

@Srikanth, did you mean to merge it? you CLOSED the pr instead.

**Comment by bmillermrn** [comment]
I was having him update the URSI to an NITEST URSI, but I was able to tweak his permissions so he can now access the NITEST person without changing this URSI. The tests now pass with the permission change, so he decided to close the PR.

**Comment by ruwang** [comment]
Gotcha. Thanks for for the info. But now I still don't know why I got the
error . lol.

**Comment by bmillermrn** [comment]
I guess we'll never know :)

**Pull request closed without merging**
